name: Container Image CI

on:
  push:
    branches: ["main"]
jobs:
  build-svc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: bcs1600-postcode-api:latest
